spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mysql://localhost:3306/grades_tatistics?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: ysp750421
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  tomcat:
    uri-encoding: utf-8
  port: 8080