spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true

  redis:
    host: 127.0.0.1
    port: 6379

  mail:
    host: smtp.qq.com
    username: 3119395617@qq.com
    password: nwhoxxsuwhniddjj
    default-encoding: utf-8

  datasource:
    url: jdbc:mysql://localhost:3306/future?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB



server:
  tomcat:
    uri-encoding: utf-8
  port: 8080

mybatis:
  configuration:
    map-underscore-to-camel-case: true


file:
  dirs: \src\main\java\img\